server:
  port: 8080

spring:
  application:
    name: stay-oline-backend

# Configurações do Stellar/Soroban - #todo: ajustar para variavels de ambiente
stellar:
  network-passphrase: "Test SDF Network ; September 2015"   # TESTNET
  horizon-url: "https://horizon-testnet.stellar.org"
  soroban-rpc-url: "https://soroban-testnet.stellar.org"    # ou http://localhost:8000/soroban/rpc no localnet
  contract-address: "C...SEU_CONTRATO"
  admin-secret-key: "S...SEU_ADMIN"
  token-asset-address: "C...TOKEN_OPCIONAL"


# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
